// Textes des pages uniques (accueil, tarifs, abonnements, parrainage, studio…)

import type { Locale } from '../routes'
import type { Faq } from './types'

const FR = {
  home: {
    metaTitle: 'Stripwork — Création de site internet, SEO et Google Ads pour TPE et PME',
    metaDesc:
      'Studio de création de sites internet, référencement SEO et Google Ads pour TPE et PME en France et en Espagne. Sites sur mesure dès 1 199 € HT, audit gratuit.',
    display: 'D’une ligne perdue à la première place.',
    h1sub: 'Création de site internet, SEO et Google Ads pour TPE et PME, en France et en Espagne.',
    lead: 'Un studio de trois personnes : on dessine votre site, on le référence et on pilote vos campagnes. Un seul interlocuteur, du premier croquis au premier appel.',
    ctaSecondary: 'Voir les tarifs',
    sceneNote: 'Exemple illustratif, entreprise fictive',
    replay: 'Rejouer',
    stepsLabel: 'Les étapes',
    steps: [
      { t: 'Perdu dans la liste', d: 'Votre entreprise existe, mais au milieu des autres, personne ne la remarque.' },
      { t: 'L’audit', d: 'On repère ce qui vous rend invisible : pas de site, fiche Google incomplète, mauvaises recherches.' },
      { t: 'Le design', d: 'Sybille dessine une identité qui ressemble à votre métier. On vous remarque enfin.' },
      { t: 'La mise en ligne', d: 'Mathieu et Louis codent un site rapide, référencé dès le premier jour.' },
      { t: 'SEO & Google Ads', d: 'Référencement et campagnes font remonter votre entreprise dans les recherches de votre zone.' },
      { t: 'Le téléphone sonne', d: 'Les demandes arrivent, et chacune est mesurée.' },
    ],
    scene: {
      rubrique: 'Électriciens',
      target: 'Martin Électricité',
      targetMeta: 'Dépannage · Rénovation',
      phone: '04 •• •• ••',
      notes: ['pas de site', 'fiche Google incomplète', 'position 27'],
      tagline: 'Dépannage & rénovation électrique',
      cta: 'Appeler',
      url: 'martin-electricite.fr',
      live: 'en ligne',
      position: 'Position',
      call: 'Nouvelle demande de devis',
      callSub: 'via le site · à l’instant',
      others: [
        'Arc Électrique', 'Bâti Élec Services', 'Borne & Watt', 'Câblage Rhône', 'Courant Continu SARL', 'Delta Électricité',
        'Éclairage Moderne', 'Élec Dépannage 24', 'Électro Confort', 'Énergie Pro', 'Fil Rouge Élec', 'Force & Lumière',
        'Général Élec', 'Haute Tension Services', 'Lumen Installation', 'Maison Élec', 'Néon & Fils', 'Ohm Rénovation',
        'Phase Neutre', 'Pro Tableau', 'Relais Électricité', 'Secteur Élec', 'Tension Plus', 'Volt Artisan',
      ],
    },
    studioH: 'Trois personnes. Un seul interlocuteur.',
    studioP:
      'Souvent, le site, le référencement et la publicité sont confiés à trois prestataires qui ne se parlent pas. Chez Stripwork, c’est la même équipe, du design aux campagnes.',
    servicesH: 'Ce que le studio fait pour vous',
    workH: 'Des sites en ligne, pas des maquettes',
    workP: 'Chaque réalisation est un vrai site, visitable aujourd’hui.',
    liveH: 'Également livrés et en ligne',
    metiersH: 'Votre métier a sa rubrique',
    metiersP: 'Chaque métier a ses urgences, ses recherches et ses preuves. Voici ceux pour lesquels on a déjà construit.',
    pricesH: 'Des prix affichés',
    pricesP: 'Même prix pour une création ou une refonte. Le suivi mensuel (SEO, Google Ads, hébergement) est à part, sans lien avec le prix du site.',
    faq: [
      { q: 'Travaillez-vous partout en France et en Espagne ?', a: 'Oui. Tout se fait à distance : appels, visio, validation en ligne. Nos clients sont en France et sur la côte espagnole.' },
      { q: 'Faites-vous des sites e-commerce ?', a: 'Non. On se concentre sur les sites vitrines, landing pages et sites B2B qui génèrent des appels et des demandes de devis.' },
      { q: 'Combien coûte un site ?', a: 'Essentiel 1 199 € HT, Signature 1 590 € HT, Sur mesure à partir de 2 300 € HT. Le nom de domaine reste à votre nom et à vos frais.' },
      { q: 'Qu’est-ce que l’audit gratuit ?', a: 'Un état des lieux de votre site, de votre fiche Google et de vos concurrents, présenté au téléphone. Gratuit et sans engagement.' },
    ] as Faq[],
    finalH: 'Commencez par l’audit gratuit',
    finalP: 'Dites-nous qui vous êtes et où vous en êtes. On regarde votre site, votre fiche Google et vos concurrents, puis on vous appelle.',
  },
  tarifs: {
    metaTitle: 'Tarifs création et refonte de site internet dès 1 199 € HT | Stripwork',
    metaDesc:
      'Nos prix affichés : Essentiel 1 199 € HT, Signature 1 590 € HT, Sur mesure dès 2 300 € HT. Création ou refonte, SEO technique inclus. Parrainage jusqu’à -50 %.',
    label: 'Tarifs',
    h1: 'Tarifs création et refonte de site internet',
    lead: 'Trois offres, des prix affichés, le même tarif pour une création ou une refonte. Le SEO technique est toujours inclus.',
    included: 'Dans chaque site',
    includedList: [
      'Design sur mesure',
      'SEO technique complet et données structurées',
      'Site rapide, pensé pour le mobile',
      'Formulaire protégé contre le spam',
      'Redirections des anciennes pages (refonte)',
      'Mise en ligne',
    ],
    notIncluded: 'À prévoir à côté',
    notIncludedList: [
      'Le nom de domaine, à votre nom et à vos frais',
      'L’hébergement : forfait optionnel à 29 € HT/mois, ou chez vous',
      'Le budget publicitaire Google Ads, le cas échéant',
    ],
    payment: 'Paiement : 50 % d’acompte à la commande, le solde à la mise en ligne.',
    plansTeaser: 'Suivi mensuel : SEO, Google Ads, hébergement',
    plansTeaserP: 'Les abonnements sont indépendants du prix du site. Ils se prennent quand vous voulez, ensemble ou séparément.',
    plansLink: 'Voir les abonnements',
    choose: 'Choisir',
    faq: [
      { q: 'Les prix sont-ils HT ?', a: 'Oui, tous nos prix sont affichés hors taxes.' },
      { q: 'Une refonte coûte-t-elle plus cher ?', a: 'Non. Même grille ; la migration SEO et les redirections sont incluses.' },
      { q: 'Et si mon projet dépasse 10 pages ?', a: 'C’est l’offre Sur mesure : on chiffre précisément après l’audit.' },
    ] as Faq[],
  },
  abonnements: {
    metaTitle: 'Abonnements SEO, Google Ads et hébergement | Stripwork',
    metaDesc:
      'Suivi mensuel de votre visibilité : SEO continu 400 € HT/mois, gestion Google Ads 400 € HT/mois hors budget, hébergement & maintenance 29 € HT/mois.',
    label: 'Abonnements',
    h1: 'Abonnements : SEO, Google Ads et hébergement',
    lead: 'Un site se construit une fois ; sa visibilité se travaille chaque mois. Ces abonnements sont indépendants du prix du site.',
    combo: 'Les abonnements se combinent librement. Vous pouvez aussi n’en prendre aucun et héberger votre site vous-même.',
    commitment: 'Durée d’engagement : [À CONFIRMER]',
    see: 'En savoir plus',
    faq: [
      { q: 'Faut-il avoir un site Stripwork pour s’abonner ?', a: 'Non. On commence alors par un audit de votre site actuel.' },
      { q: 'Le budget Google Ads est-il compris ?', a: 'Non : les 400 € HT couvrent notre travail, le budget est payé directement à Google.' },
    ] as Faq[],
  },
  parrainage: {
    metaTitle: 'Parrainage : -10 % par entreprise recommandée, jusqu’à -50 % | Stripwork',
    metaDesc:
      'Recommandez Stripwork à d’autres entreprises : chaque rendez-vous tenu retire 10 % du prix de votre site, jusqu’à 5 recommandations soit -50 % sur votre site.',
    label: 'Parrainage',
    h1: 'Parrainage : jusqu’à -50 % sur votre site',
    lead: 'Vous connaissez d’autres entreprises qui ont besoin d’un site, de SEO ou de Google Ads ? Chaque entreprise recommandée qui tient un rendez-vous avec nous retire 10 % du prix de votre site, déduits du solde.',
    card: 'Carte de parrainage',
    stamp: 'RDV tenu',
    howH: 'Comment ça marche',
    how: [
      'Vous passez commande de votre site.',
      'Vous parlez de nous à une entreprise ; elle indique votre nom dans notre formulaire ou au téléphone.',
      'Dès que son rendez-vous avec nous a eu lieu, 10 % du prix du site sont déduits de votre solde.',
      'Jusqu’à 5 rendez-vous, soit -50 % : c’est exactement le solde de votre site, offert.',
    ],
    rulesH: 'Ce qui compte comme un rendez-vous',
    rules: [
      'Une entreprise immatriculée (SIRET en France, NIF en Espagne)',
      'Un besoin réel : site, refonte, SEO ou Google Ads',
      'Le décideur présent au rendez-vous',
      'Une entreprise qui n’était pas déjà en contact avec nous',
    ],
    afterH: 'Après la mise en ligne',
    after: 'Les rendez-vous tenus jusqu’à 90 jours après la mise en ligne comptent aussi : ils vous sont remboursés par virement, toujours dans la limite de -50 %.',
    example: 'Exemple : site Essentiel à 1 199 € HT. Acompte 599,50 €. Avec 5 rendez-vous tenus, le solde de 599,50 € est offert.',
    cta: 'Vous êtes recommandé par un client ? Indiquez son nom dans le formulaire d’audit.',
  },
  studio: {
    metaTitle: 'Le studio Stripwork : design, développement, SEO et Google Ads',
    metaDesc:
      'Stripwork est un studio de trois personnes : Sybille Guinard (direction artistique), Mathieu Jannolfo (développement, SEO & SEA), Louis Jannolfo (développement, data).',
    label: 'Le studio',
    h1: 'Le studio Stripwork',
    lead: 'Trois personnes, trois métiers complémentaires, une seule équipe qui suit votre projet du premier croquis au premier appel.',
    howH: 'Notre façon de travailler',
    how: [
      { t: 'Rien d’inventé', d: 'Pas d’avis fabriqués, pas de chiffres gonflés, pas de promesse de première place. Uniquement ce qui est vrai et vérifiable.' },
      { t: 'Le métier d’abord', d: 'Chaque site part de votre métier et de vos clients, jamais d’un modèle.' },
      { t: 'Aucun abonnement imposé', d: 'Le domaine est à votre nom, et le suivi mensuel reste un choix.' },
      { t: 'En français et en espagnol', d: 'Nos clients sont en France et en Espagne ; on travaille dans les deux langues.' },
    ],
    notH: 'Ce qu’on ne fait pas',
    not: 'Pas d’e-commerce, pas de sites à partir de thèmes, pas de promesses de position garantie.',
  },
  audit: {
    metaTitle: 'Audit gratuit de votre site et de votre visibilité Google | Stripwork',
    metaDesc:
      'Audit gratuit et sans engagement : votre site, votre fiche Google, vos campagnes et vos concurrents passés en revue, résultats présentés au téléphone.',
    label: 'Audit gratuit',
    h1: 'Audit gratuit de votre site et de votre visibilité',
    lead: 'On regarde votre site, votre fiche Google, vos éventuelles campagnes et vos concurrents. Puis on vous appelle pour vous présenter ce qu’on a trouvé. Gratuit et sans engagement.',
    checksH: 'Ce qu’on regarde',
    checks: [
      'Votre site : vitesse, mobile, pages, référencement technique',
      'Votre fiche Google : catégories, avis, photos, informations',
      'Vos concurrents : qui apparaît devant vous, et pourquoi',
      'Vos campagnes Google Ads, si vous en avez',
    ],
    formH: 'Demander l’audit',
  },
  contact: {
    metaTitle: 'Contact | Stripwork — studio web, SEO et Google Ads',
    metaDesc: 'Contactez le studio Stripwork pour votre site internet, votre référencement ou vos campagnes Google Ads.',
    label: 'Contact',
    h1: 'Contacter le studio',
    lead: 'Un projet, une question, une recommandation : écrivez-nous. Pour un premier contact, l’audit gratuit est souvent le plus utile.',
    emailLabel: 'Par e-mail',
    formH: 'Nous écrire',
  },
  realisations: {
    metaTitle: 'Réalisations : sites internet, SEO et Google Ads | Stripwork',
    metaDesc:
      'Les sites créés par le studio Stripwork : électricien, paysagiste, chaudronnerie, thérapeutes, restaurant… Tous en ligne et visitables.',
    label: 'Réalisations',
    h1: 'Réalisations',
    lead: 'Des sites en ligne, pour de vraies entreprises. Chaque étude de cas raconte le problème, ce qu’on a construit et ce que ça a changé.',
    appsH: 'Applications iOS',
    appsP: 'Le studio conçoit aussi des applications, de A à Z.',
    problem: 'Le problème',
    built: 'Ce qu’on a construit',
    strategy: 'La stratégie',
    result: 'Le résultat',
    next: 'Réalisation suivante',
  },
  conseils: {
    metaTitle: 'Conseils : sites internet, SEO et Google Ads | Stripwork',
    metaDesc: 'Guides pratiques pour TPE et PME : prix d’un site, refonte sans perte de référencement, SEO local, Google Ads.',
    label: 'Conseils',
    h1: 'Conseils',
    lead: 'Des guides courts et honnêtes pour décider en connaissance de cause.',
    read: 'Lire',
    sources: 'Sources',
    related: 'À lire aussi',
    published: 'Publié le',
  },
  notFound: {
    h1: 'Cette page n’est pas dans l’annuaire.',
    p: 'L’adresse a peut-être changé. Voici les rubriques principales :',
  },
  metierPage: {
    searches: 'Ce que vos clients tapent',
    searchesNote: 'Exemples de recherches',
    features: 'Ce que votre site doit faire',
    proof: 'Nos sites dans cette rubrique',
    otherMetiers: 'Autres rubriques',
  },
  servicePage: {
    points: 'Ce que vous obtenez',
    proof: 'Exemples',
    more: 'Dans cette rubrique',
    related: 'Voir aussi',
  },
}

type PagesDict = typeof FR

const ES: PagesDict = {
  home: {
    metaTitle: 'Stripwork — Diseño web, SEO y Google Ads para pymes y autónomos',
    metaDesc:
      'Estudio de diseño web, posicionamiento SEO y Google Ads para pymes y autónomos en España y Francia. Webs a medida desde 1199 € + IVA, auditoría gratuita.',
    display: 'De una línea perdida al primer puesto.',
    h1sub: 'Diseño web, posicionamiento SEO y Google Ads para pymes y autónomos, en España y Francia.',
    lead: 'Un estudio de tres personas: diseñamos su web, la posicionamos y gestionamos sus campañas. Un único interlocutor, del primer boceto a la primera llamada.',
    ctaSecondary: 'Ver precios',
    sceneNote: 'Ejemplo ilustrativo, empresa ficticia',
    replay: 'Repetir',
    stepsLabel: 'Las etapas',
    steps: [
      { t: 'Perdido en la lista', d: 'Su empresa existe, pero entre tantas otras nadie la ve.' },
      { t: 'La auditoría', d: 'Detectamos lo que le hace invisible: sin web, ficha de Google incompleta, búsquedas equivocadas.' },
      { t: 'El diseño', d: 'Sybille diseña una identidad que se parece a su oficio. Por fin le ven.' },
      { t: 'La publicación', d: 'Mathieu y Louis programan una web rápida, posicionada desde el primer día.' },
      { t: 'SEO y Google Ads', d: 'Posicionamiento y campañas hacen subir su empresa en las búsquedas de su zona.' },
      { t: 'Suena el teléfono', d: 'Llegan las peticiones, y cada una queda medida.' },
    ],
    scene: {
      rubrique: 'Electricistas',
      target: 'Electricidad Martín',
      targetMeta: 'Urgencias · Reformas',
      phone: '96 ••• ••',
      notes: ['sin web', 'ficha de Google incompleta', 'posición 27'],
      tagline: 'Urgencias y reformas eléctricas',
      cta: 'Llamar',
      url: 'electricidad-martin.es',
      live: 'publicada',
      position: 'Posición',
      call: 'Nueva petición de presupuesto',
      callSub: 'desde la web · ahora mismo',
      others: [
        'Alta Tensión Levante', 'Amperio Instalaciones', 'Borne y Vatio', 'Cableados del Sur', 'Corriente Continua SL', 'Delta Electricidad',
        'Eléctrica Costa', 'Electro Confort', 'Energía Pro', 'Fase Neutra', 'Fuerza y Luz', 'Hilo Rojo',
        'Iluminación Moderna', 'Instalaciones Rápidas', 'Lumen Servicios', 'Montajes Eléctricos', 'Neón y Cables', 'Ohmio Reformas',
        'Pro Cuadros', 'Relé Electricidad', 'Sector Eléctrico', 'Tensión Plus', 'Voltio Artesano', 'Watt Hogar',
      ],
    },
    studioH: 'Tres personas. Un único interlocutor.',
    studioP:
      'A menudo la web, el posicionamiento y la publicidad dependen de tres proveedores que no hablan entre sí. En Stripwork es el mismo equipo, del diseño a las campañas.',
    servicesH: 'Lo que el estudio hace por usted',
    workH: 'Webs publicadas, no maquetas',
    workP: 'Cada proyecto es una web real que puede visitar hoy.',
    liveH: 'También entregadas y publicadas',
    metiersH: 'Su sector tiene su sección',
    metiersP: 'Cada oficio tiene sus urgencias, sus búsquedas y sus pruebas. Estos son los sectores para los que ya hemos trabajado.',
    pricesH: 'Precios publicados',
    pricesP: 'Mismo precio para una web nueva o un rediseño. El seguimiento mensual (SEO, Google Ads, alojamiento) va aparte, sin relación con el precio de la web.',
    faq: [
      { q: '¿Trabajan en toda España y Francia?', a: 'Sí. Todo se hace a distancia: llamadas, videollamadas, validación online. Nuestros clientes están en Francia y en la costa española.' },
      { q: '¿Hacen tiendas online?', a: 'No. Nos centramos en webs corporativas, landing pages y webs B2B que generan llamadas y peticiones de presupuesto.' },
      { q: '¿Cuánto cuesta una web?', a: 'Esencial 1199 €, Firma 1590 €, A medida desde 2300 € (+ IVA). El dominio queda a su nombre y a su cargo.' },
      { q: '¿Qué es la auditoría gratuita?', a: 'Un diagnóstico de su web, su ficha de Google y su competencia, presentado por teléfono. Gratis y sin compromiso.' },
    ],
    finalH: 'Empiece por la auditoría gratuita',
    finalP: 'Cuéntenos quién es y en qué punto está. Revisamos su web, su ficha de Google y su competencia, y le llamamos.',
  },
  tarifs: {
    metaTitle: 'Precios de diseño y rediseño web desde 1199 € | Stripwork',
    metaDesc:
      'Precios publicados: Esencial 1199 €, Firma 1590 €, A medida desde 2300 € (+ IVA). Web nueva o rediseño, SEO técnico incluido. Programa de referidos hasta -50 %.',
    label: 'Precios',
    h1: 'Precios de diseño y rediseño web',
    lead: 'Tres planes, precios publicados y la misma tarifa para una web nueva o un rediseño. El SEO técnico siempre está incluido.',
    included: 'En cada web',
    includedList: [
      'Diseño a medida',
      'SEO técnico completo y datos estructurados',
      'Web rápida, pensada para el móvil',
      'Formulario protegido contra spam',
      'Redirecciones de las páginas antiguas (rediseño)',
      'Publicación',
    ],
    notIncluded: 'A tener en cuenta',
    notIncludedList: [
      'El dominio, a su nombre y a su cargo',
      'El alojamiento: plan opcional de 29 € + IVA/mes, o por su cuenta',
      'La inversión en Google Ads, si procede',
    ],
    payment: 'Pago: 50 % de anticipo al encargar, el resto en la publicación.',
    plansTeaser: 'Seguimiento mensual: SEO, Google Ads, alojamiento',
    plansTeaserP: 'Los planes mensuales son independientes del precio de la web. Se contratan cuando quiera, juntos o por separado.',
    plansLink: 'Ver los planes mensuales',
    choose: 'Elegir',
    faq: [
      { q: '¿Los precios incluyen IVA?', a: 'No, todos nuestros precios se muestran sin IVA.' },
      { q: '¿Un rediseño cuesta más?', a: 'No. Misma tarifa; la migración SEO y las redirecciones están incluidas.' },
      { q: '¿Y si mi proyecto supera las 10 páginas?', a: 'Es el plan A medida: lo presupuestamos con precisión tras la auditoría.' },
    ],
  },
  abonnements: {
    metaTitle: 'Planes mensuales de SEO, Google Ads y alojamiento | Stripwork',
    metaDesc:
      'Seguimiento mensual de su visibilidad: SEO continuo 400 €/mes, gestión de Google Ads 400 €/mes sin inversión, alojamiento y mantenimiento 29 €/mes (+ IVA).',
    label: 'Planes mensuales',
    h1: 'Planes mensuales: SEO, Google Ads y alojamiento',
    lead: 'Una web se construye una vez; su visibilidad se trabaja cada mes. Estos planes son independientes del precio de la web.',
    combo: 'Los planes se combinan libremente. También puede no contratar ninguno y alojar la web por su cuenta.',
    commitment: 'Permanencia: [À CONFIRMER]',
    see: 'Saber más',
    faq: [
      { q: '¿Hace falta una web de Stripwork para contratar?', a: 'No. En ese caso empezamos con una auditoría de su web actual.' },
      { q: '¿La inversión en Google Ads está incluida?', a: 'No: los 400 € + IVA cubren nuestro trabajo, la inversión se paga directamente a Google.' },
    ],
  },
  parrainage: {
    metaTitle: 'Programa de referidos: -10 % por empresa recomendada | Stripwork',
    metaDesc:
      'Recomiende Stripwork a otras empresas: cada reunión realizada descuenta un 10 % del precio de su web, hasta 5 recomendaciones, es decir -50 % en su web.',
    label: 'Referidos',
    h1: 'Programa de referidos: hasta -50 % en su web',
    lead: '¿Conoce empresas que necesitan una web, SEO o Google Ads? Cada empresa recomendada que tenga una reunión con nosotros descuenta un 10 % del precio de su web, deducido del pago final.',
    card: 'Tarjeta de referidos',
    stamp: 'Reunión hecha',
    howH: 'Cómo funciona',
    how: [
      'Encarga su web.',
      'Habla de nosotros a una empresa; ella indica su nombre en nuestro formulario o por teléfono.',
      'En cuanto se celebra su reunión con nosotros, se descuenta un 10 % del precio de la web de su pago final.',
      'Hasta 5 reuniones, es decir -50 %: exactamente el pago final de su web, gratis.',
    ],
    rulesH: 'Qué cuenta como reunión',
    rules: [
      'Una empresa registrada (NIF en España, SIRET en Francia)',
      'Una necesidad real: web, rediseño, SEO o Google Ads',
      'La persona que decide, presente en la reunión',
      'Una empresa que no estuviera ya en contacto con nosotros',
    ],
    afterH: 'Después de la publicación',
    after: 'Las reuniones realizadas hasta 90 días después de la publicación también cuentan: se le reembolsan por transferencia, siempre con el límite de -50 %.',
    example: 'Ejemplo: web Esencial de 1199 € + IVA. Anticipo 599,50 €. Con 5 reuniones realizadas, el pago final de 599,50 € es gratis.',
    cta: '¿Le recomienda un cliente? Indique su nombre en el formulario de auditoría.',
  },
  studio: {
    metaTitle: 'El estudio Stripwork: diseño, desarrollo, SEO y Google Ads',
    metaDesc:
      'Stripwork es un estudio de tres personas: Sybille Guinard (dirección de arte), Mathieu Jannolfo (desarrollo, SEO y SEM), Louis Jannolfo (desarrollo, datos).',
    label: 'El estudio',
    h1: 'El estudio Stripwork',
    lead: 'Tres personas, tres oficios complementarios y un único equipo que sigue su proyecto del primer boceto a la primera llamada.',
    howH: 'Cómo trabajamos',
    how: [
      { t: 'Nada inventado', d: 'Sin reseñas fabricadas, sin cifras infladas, sin promesas de primer puesto. Solo lo verdadero y verificable.' },
      { t: 'Primero el oficio', d: 'Cada web parte de su oficio y sus clientes, nunca de una plantilla.' },
      { t: 'Ningún plan obligatorio', d: 'El dominio está a su nombre y el seguimiento mensual es opcional.' },
      { t: 'En español y en francés', d: 'Nuestros clientes están en España y Francia; trabajamos en ambos idiomas.' },
    ],
    notH: 'Lo que no hacemos',
    not: 'Ni tiendas online, ni webs con plantillas, ni promesas de posición garantizada.',
  },
  audit: {
    metaTitle: 'Auditoría gratuita de su web y su visibilidad en Google | Stripwork',
    metaDesc:
      'Auditoría gratuita y sin compromiso: su web, su ficha de Google, sus campañas y su competencia, con los resultados presentados por teléfono.',
    label: 'Auditoría gratuita',
    h1: 'Auditoría gratuita de su web y su visibilidad',
    lead: 'Revisamos su web, su ficha de Google, sus campañas si las tiene y su competencia. Después le llamamos para contarle lo que hemos encontrado. Gratis y sin compromiso.',
    checksH: 'Qué revisamos',
    checks: [
      'Su web: velocidad, móvil, páginas, SEO técnico',
      'Su ficha de Google: categorías, reseñas, fotos, información',
      'Su competencia: quién aparece delante de usted, y por qué',
      'Sus campañas de Google Ads, si las tiene',
    ],
    formH: 'Pedir la auditoría',
  },
  contact: {
    metaTitle: 'Contacto | Stripwork — estudio web, SEO y Google Ads',
    metaDesc: 'Contacte con el estudio Stripwork para su web, su posicionamiento o sus campañas de Google Ads.',
    label: 'Contacto',
    h1: 'Contactar con el estudio',
    lead: 'Un proyecto, una pregunta, una recomendación: escríbanos. Para un primer contacto, la auditoría gratuita suele ser lo más útil.',
    emailLabel: 'Por correo',
    formH: 'Escríbanos',
  },
  realisations: {
    metaTitle: 'Proyectos: diseño web, SEO y Google Ads | Stripwork',
    metaDesc:
      'Las webs creadas por el estudio Stripwork: terapeutas, electricista, paisajista, calderería, restaurante… Todas publicadas y visitables.',
    label: 'Proyectos',
    h1: 'Proyectos',
    lead: 'Webs publicadas para empresas reales. Cada caso cuenta el problema, lo que construimos y lo que cambió.',
    appsH: 'Aplicaciones iOS',
    appsP: 'El estudio también diseña y desarrolla aplicaciones de principio a fin.',
    problem: 'El problema',
    built: 'Lo que construimos',
    strategy: 'La estrategia',
    result: 'El resultado',
    next: 'Siguiente proyecto',
  },
  conseils: {
    metaTitle: 'Blog: diseño web, SEO y Google Ads | Stripwork',
    metaDesc: 'Guías prácticas para pymes y autónomos: precio de una web, rediseño sin perder posicionamiento, SEO local, Google Ads.',
    label: 'Blog',
    h1: 'Blog',
    lead: 'Guías cortas y honestas para decidir con conocimiento de causa.',
    read: 'Leer',
    sources: 'Fuentes',
    related: 'Lea también',
    published: 'Publicado el',
  },
  notFound: {
    h1: 'Esta página no está en la guía.',
    p: 'Puede que la dirección haya cambiado. Estas son las secciones principales:',
  },
  metierPage: {
    searches: 'Lo que buscan sus clientes',
    searchesNote: 'Ejemplos de búsquedas',
    features: 'Lo que debe hacer su web',
    proof: 'Nuestras webs en esta sección',
    otherMetiers: 'Otras secciones',
  },
  servicePage: {
    points: 'Lo que obtiene',
    proof: 'Ejemplos',
    more: 'En esta sección',
    related: 'Ver también',
  },
}

export function pages(locale: Locale): PagesDict {
  return locale === 'fr' ? FR : ES
}
